# Generated by Django 4.0.4 on 2022-05-25 12:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Post', tinymce.models.HTMLField()),
                ('pub_date', models.DateField(verbose_name='Date Published')),
                ('pub_time', models.TimeField(verbose_name='Time Published')),
            ],
        ),
    ]
