# Generated by Django 4.0.4 on 2022-05-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_time',
            field=models.TimeField(auto_now=True, verbose_name='Time Published'),
        ),
    ]
