# Generated by Django 4.0.4 on 2022-05-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_profile_posts_blogpost_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='posts',
            new_name='Author',
        ),
    ]
