# Generated by Django 4.0.4 on 2022-05-31 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
        ('blog', '0005_rename_posts_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='BlogPost',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
