# Generated by Django 4.0.4 on 2022-05-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(upload_to='./profile/<django.db.models.fields.CharField>/', verbose_name='Profile Image'),
        ),
    ]
